@startuml  class 

' time + source_id (foreign) + destination_id (foreign) could be a primary key
struct Message{
    ID : MessageID
    Source : UserID
    Destination : UserID
    Time : time.Time
    Content : MessageContent
}

struct User{
    ID : UserID
    Name : string
    IP : net.IP
    port: int
}

struct Conversation{
    MessageBodies : []MessageBody
}

Conversation --o "0..*" Message
@enduml