@startuml  class 

' time + source_id (foreign) + destination_id (foreign) could be a primary key
struct Message{
    ID : MessageID
    Source : UserID
    Destination : UserID
    Body : MessageBody
}

struct MessageBody{
    Time : time.Time
    Content : MessageContent
}

struct User{
    ID : UserID
    Name : string
    IP : net.IP
    port: int
}

struct Conversation{
    User : UserID
    Other : UserID
    MessageBodies : []MessageBody
}

Conversation --o "0..*" MessageBody
Message --o "1" MessageBody

@enduml